/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BloodGroupService } from "../bloodGroup.service";
import { BloodGroupCreateInput } from "./BloodGroupCreateInput";
import { BloodGroup } from "./BloodGroup";
import { BloodGroupFindManyArgs } from "./BloodGroupFindManyArgs";
import { BloodGroupWhereUniqueInput } from "./BloodGroupWhereUniqueInput";
import { BloodGroupUpdateInput } from "./BloodGroupUpdateInput";
import { BloodBankFindManyArgs } from "../../bloodBank/base/BloodBankFindManyArgs";
import { BloodBank } from "../../bloodBank/base/BloodBank";
import { BloodBankWhereUniqueInput } from "../../bloodBank/base/BloodBankWhereUniqueInput";
import { DonorFindManyArgs } from "../../donor/base/DonorFindManyArgs";
import { Donor } from "../../donor/base/Donor";
import { DonorWhereUniqueInput } from "../../donor/base/DonorWhereUniqueInput";

export class BloodGroupControllerBase {
  constructor(protected readonly service: BloodGroupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BloodGroup })
  async createBloodGroup(
    @common.Body() data: BloodGroupCreateInput
  ): Promise<BloodGroup> {
    return await this.service.createBloodGroup({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [BloodGroup] })
  @ApiNestedQuery(BloodGroupFindManyArgs)
  async bloodGroups(@common.Req() request: Request): Promise<BloodGroup[]> {
    const args = plainToClass(BloodGroupFindManyArgs, request.query);
    return this.service.bloodGroups({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BloodGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async bloodGroup(
    @common.Param() params: BloodGroupWhereUniqueInput
  ): Promise<BloodGroup | null> {
    const result = await this.service.bloodGroup({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BloodGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBloodGroup(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() data: BloodGroupUpdateInput
  ): Promise<BloodGroup | null> {
    try {
      return await this.service.updateBloodGroup({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BloodGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBloodGroup(
    @common.Param() params: BloodGroupWhereUniqueInput
  ): Promise<BloodGroup | null> {
    try {
      return await this.service.deleteBloodGroup({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bloodBanks")
  @ApiNestedQuery(BloodBankFindManyArgs)
  async findBloodBanks(
    @common.Req() request: Request,
    @common.Param() params: BloodGroupWhereUniqueInput
  ): Promise<BloodBank[]> {
    const query = plainToClass(BloodBankFindManyArgs, request.query);
    const results = await this.service.findBloodBanks(params.id, {
      ...query,
      select: {
        availability: true,

        bloodGroup: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bloodBanks")
  async connectBloodBanks(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: BloodBankWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodBanks: {
        connect: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bloodBanks")
  async updateBloodBanks(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: BloodBankWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodBanks: {
        set: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bloodBanks")
  async disconnectBloodBanks(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: BloodBankWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodBanks: {
        disconnect: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/donors")
  @ApiNestedQuery(DonorFindManyArgs)
  async findDonors(
    @common.Req() request: Request,
    @common.Param() params: BloodGroupWhereUniqueInput
  ): Promise<Donor[]> {
    const query = plainToClass(DonorFindManyArgs, request.query);
    const results = await this.service.findDonors(params.id, {
      ...query,
      select: {
        age: true,
        available: true,

        bloodGroup: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        weight: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/donors")
  async connectDonors(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: DonorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donors: {
        connect: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/donors")
  async updateDonors(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: DonorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donors: {
        set: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/donors")
  async disconnectDonors(
    @common.Param() params: BloodGroupWhereUniqueInput,
    @common.Body() body: DonorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donors: {
        disconnect: body,
      },
    };
    await this.service.updateBloodGroup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
